language: node_js
node_js:
- 7.10.1
before_script:
- npm install -g gulp-cli
script: gulp
before_deploy:
- cp -r public/images deploy/
- cp -r public/scripts deploy/
- cp -r public/styles deploy/
- cp -r public/*.html deploy/
deploy:
  provider: s3
  access_key_id: AKIAITZUUGIJNKLB4PHA
  secret_access_key:
    secure: dT7TiOczk0rTjXHhLAD9fZa1kbUZ8LCgF4d3tVI7RIxP5PswqcxGGeevjGAnVde1minkBEZcnfKgDKN4aWy6O9nnZagRmqB++KbrNgJiyWcCnw6tfqNvHXfc/VWx9sNoBs73/kc4irB5WWDbQzlYxdQuj/L7lLxrXWAD+xSJ+Y8X6G+1VnnVyX/bDzaTZyu4UNccjWRkbRKXPTN2WiZ6DlRy2RWZUxc9P+nXwmR1ogX7F/lSHCCLAmu0shoj0EfUPnKM13JO4iFpNCFDXRLwOsdY3sXkGmDZPPFE22cdbU74XQ/PzxsBcMaXnwNbC1XKu7t/BtpnAPTv7MOLJx/T3WsW7KhIB9nY8UNvUgUMyNRsxQojluxiXNhjs5jFzo9urow7stNqGh/T9zE1iwyAHZHlZ3qwDBVNb5PFt54BCUH+rSTz/bzpj9L/Hw5S4PaXgQ2I4deSIvL3nirbRuLbuX31K6U6H4TrIUSr+CLjeijk1rYgOZecBtHuuFoC6rcIicVqOBS6sY6ZKoWJNtgcPhiVnvrvuwieogvFU8tiaAjxFCnHPPbwPwlh52Bn0sBr4j9Py/gKP5UJMCvoSfyzjY1R9l87WmMCzdkxjiAOfhQ0tzdsMrxiT/LC/uF9juxqCeCuaHcEfO9JTCaDU2/yrjnXpJrcK3W5mtevLVZrbl4=
  bucket: static.moveon.org
  region: us-east-2
  local-dir: deploy
  upload-dir: giraffe
  acl: public_read
  on:
    branch: main
  skip_cleanup: true
