language: node_js
node_js:
- 7.10.1
before_script:
- npm install -g gulp-cli
script: gulp
before_deploy:
- cp -r public/images deploy/
- cp -r public/scripts deploy/
- cp -r public/styles deploy/
- cp -r public/*.html deploy/
deploy:
  provider: s3
  on:
    branch: main
  access_key_id: AKIAITZUUGIJNKLB4PHA
  bucket: static.moveon.org
  skip_cleanup: true
  region: us-east-2
  acl: public_read
  local_dir: deploy
  upload-dir: giraffe
  secret_access_key:
    secure: OA27ZyMZGkiRe0zoi1/hH0vaR4cBA69PCU0g3RtNJmP1JdCS4tzf5whD7dynsvr+ccugjOncAOTmlP19bTwqB/hOGAyqbCPNoSQnS9kEPrtfFSQinx62ugiglbSQ7lHWmIsGT4TuMyIP0P+GJhLOAJJDNYrX2b8crNQm2hWBtRk6R+CLuBmhpQQlyVf5qfYKwj7dEJkABU+/omdh0emnbE/ghBYTijJI6qi7ARLKGrECh4MHP4pAetb2Cih9OK+lOUf74MOEmdspvQGzgC+XxNByXexW8aKtGwhEWHmQo20xnLHoUkrZtB5JIGJFkDjJHYnidKtGEs4IgnmQpkDZsJeuBEXlFGvbJYbud9WuKbGAGmydWBi7lkAVBcR8gAfUm5mr2273+xR3pixB9SjFsVlZHJKTEV+aRKbNTx6drbYvChQl6XtaoKEfvqzixBVIpDQ3WV/gQZV+pUu2O1zOkbCb459w3gJ6TQ9M9dNScmHQIehSxuBpOHPw3RyeTL93p0cD8vm0u6ar4VuliP2X9kGu66k7lVcz/NQBcLTyuktLuIxrwB2HO+MsoGoukbh12bx20gK4ooGUVv2RQMQf832+LnnQ0HYKDZEJ+O8T3XQaEnLMs5T55aWXn8Lh7m9QRvtwealzMWfSaNn3eQE2xhHZN5PJ3GOQJcEPOpNRUhA=
