language: node_js
node_js:
- 7.10.1
before_script:
- npm install -g gulp-cli
script: gulp
before_deploy:
- cp -r public/images deploy/
- cp -r public/scripts deploy/
- cp -r public/styles deploy/
- cp -r public/*.html deploy/
deploy:
- provider: s3
  on:
    branch: main
  access_key_id: AKIAITZUUGIJNKLB4PHA
  bucket: static.moveon.org
  skip_cleanup: true
  region: us-east-2
  acl: public_read
  local_dir: deploy
  upload-dir: giraffe
  secret_access_key:
    secure: U8GNc50OXXuYCNXnBEpsKZpuM3kurpf4v9m+SsZsKI22xy1b9xSsz5HzaqthYnPT7SFi2mehtxM93/4bFBLrJq8br+zgsf3+AIuSJFYjWTW/n5OF1hO0fH2Eukcw43b4ldhjPDHlqgadShWnVSPOAbDaE4scLEfF0XnhhS+lnDP6It/5TDeTnXQxP22l9PYp7UJDm8fpKfNxruDxmewDWmZf61DiMfnTRzBRtn04h7HsRjVI8AeV67bExQigY36cde09TmCA/gtXDdKDHkn/tyPItC0lO4/3d+CBvLwwG8HNbB48BF4Q1XCvagf91URMvkumqVJtK5Cy5dmcQw5bIqVbScXvIk9sJn46zZAAiuKdEe/VgleCIhVzWZF+exTvwYLppaM97VEkRf4uQJNha2+YjP55bOsX/y/EYIivSykT4//Rm+EbNKXphmLJqDVcKAa7mbjPyLdvlEaqIqN3nFVVhud0sdfGTixCjDnTmLzv7JQIm8DLgkGjCbQQVNS1dZFagViuDlRCyGjJ7F+1NMeKzSD2I3ot9OttmgTzubdDSWohX205CcOKf0wd8w9F20gLJtqetAjRN87LHIsS2v40cLl2HYWngur2ntwvQAHh973hOaSSxuLvD3igHQ0MHlAY/Z/2jek5PUZva1edLYIb6685SmUps52qMWHMGFE=

- provider: s3
  on:
    branch: main
  access_key_id: AKIAITZUUGIJNKLB4PHA
  bucket: mop-static-stage
  skip_cleanup: true
  region: us-west-1
  acl: public_read
  local_dir: deploy
  upload-dir: giraffe
  secret_access_key:
    secure: U8GNc50OXXuYCNXnBEpsKZpuM3kurpf4v9m+SsZsKI22xy1b9xSsz5HzaqthYnPT7SFi2mehtxM93/4bFBLrJq8br+zgsf3+AIuSJFYjWTW/n5OF1hO0fH2Eukcw43b4ldhjPDHlqgadShWnVSPOAbDaE4scLEfF0XnhhS+lnDP6It/5TDeTnXQxP22l9PYp7UJDm8fpKfNxruDxmewDWmZf61DiMfnTRzBRtn04h7HsRjVI8AeV67bExQigY36cde09TmCA/gtXDdKDHkn/tyPItC0lO4/3d+CBvLwwG8HNbB48BF4Q1XCvagf91URMvkumqVJtK5Cy5dmcQw5bIqVbScXvIk9sJn46zZAAiuKdEe/VgleCIhVzWZF+exTvwYLppaM97VEkRf4uQJNha2+YjP55bOsX/y/EYIivSykT4//Rm+EbNKXphmLJqDVcKAa7mbjPyLdvlEaqIqN3nFVVhud0sdfGTixCjDnTmLzv7JQIm8DLgkGjCbQQVNS1dZFagViuDlRCyGjJ7F+1NMeKzSD2I3ot9OttmgTzubdDSWohX205CcOKf0wd8w9F20gLJtqetAjRN87LHIsS2v40cLl2HYWngur2ntwvQAHh973hOaSSxuLvD3igHQ0MHlAY/Z/2jek5PUZva1edLYIb6685SmUps52qMWHMGFE=