language: node_js
node_js:
- 8.4.0
before_script:
- npm install -g gulp-cli
script: gulp
before_deploy:
- cp -r public/images deploy/
- cp -r public/scripts deploy/
- cp -r public/styles deploy/
- cp -r public/styleguide deploy/
- cp -r public/*.html deploy/
deploy:
  - provider: s3
    on:
      branch: main
    access_key_id: AKIA3AO6RW2Y3RZOP56E
    bucket: static.moveon.org
    skip_cleanup: true
    region: us-east-2
    acl: public_read
    cache_control: max-age=31536000
    local_dir: deploy
    upload-dir: giraffe
    secret_access_key:
      secure: JdxkbHM9Stvr8/3agh7Yg3E8VSLVUWWpAVQukmx4R93uQCZV6n8vI7sg95EpZxc7IVNoOALqPhs9o66NpHecZRRVbrJAPwGnq2esH7LHcx09qMhkWjiWUgrQX032HXMI4kQcbjHJjwHFOL2qw5bz6R4RV/DTLBq8LINfJx8XY1bGnmXyYmsD7q5LE84d4/8oZW8mCresbmKkiuhCxlnGoAdUl6qif8hn/ZlR9MH42nJia3HLZmXrBTSzkmFkpX83NN0P7gsEjiEtrKuUxk32lkbW8HEh4zyncvnK8zWz9RiM2cptoDNA7+IEF6A1ps3LOQiMG6YQ5pFxoxd/wdB0ztz0gSGNUwdf8Z+tMLV0F/yomfUMAWYGK6kUhFddY6pu6i39Ly99J7bJ4RR19VSyyKZ/4uRuhar0/CGXQWRCdp+z1C/3/iN2Yb0hn77dkwk6stvLDbDiA0guOEv8kbVsD1eYXy87TcGgU0JOMtzjdsJG+Hg/uCS+LQ8GNmh/3dDrXheqWsB8hTcxtAijdsECWGYPHVCdhqsqn6zEnDxUwFWG/ZgAs2+8WDGJZqbAor24ASQL7JUnaxof8NciodnmIZnSWkyoMv6dpzNx4bsr0ttMyEH8NdncWmyiWp2T+hxmpbTcPMHqcpFAnEO8ZnqjacdVBdPngxHImZyF50IVXnQ=
  - provider: s3
    on:
      branch: main
    access_key_id: AKIA3AO6RW2Y3RZOP56E
    bucket: static.moveon.org
    skip_cleanup: true
    region: us-east-2
    acl: public_read
    local_dir: deploy
    upload-dir: giraffe-staging
    secret_access_key:
      secure: JdxkbHM9Stvr8/3agh7Yg3E8VSLVUWWpAVQukmx4R93uQCZV6n8vI7sg95EpZxc7IVNoOALqPhs9o66NpHecZRRVbrJAPwGnq2esH7LHcx09qMhkWjiWUgrQX032HXMI4kQcbjHJjwHFOL2qw5bz6R4RV/DTLBq8LINfJx8XY1bGnmXyYmsD7q5LE84d4/8oZW8mCresbmKkiuhCxlnGoAdUl6qif8hn/ZlR9MH42nJia3HLZmXrBTSzkmFkpX83NN0P7gsEjiEtrKuUxk32lkbW8HEh4zyncvnK8zWz9RiM2cptoDNA7+IEF6A1ps3LOQiMG6YQ5pFxoxd/wdB0ztz0gSGNUwdf8Z+tMLV0F/yomfUMAWYGK6kUhFddY6pu6i39Ly99J7bJ4RR19VSyyKZ/4uRuhar0/CGXQWRCdp+z1C/3/iN2Yb0hn77dkwk6stvLDbDiA0guOEv8kbVsD1eYXy87TcGgU0JOMtzjdsJG+Hg/uCS+LQ8GNmh/3dDrXheqWsB8hTcxtAijdsECWGYPHVCdhqsqn6zEnDxUwFWG/ZgAs2+8WDGJZqbAor24ASQL7JUnaxof8NciodnmIZnSWkyoMv6dpzNx4bsr0ttMyEH8NdncWmyiWp2T+hxmpbTcPMHqcpFAnEO8ZnqjacdVBdPngxHImZyF50IVXnQ=
 
