name: Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '10'
        cache: 'npm'

    - name: Setup Python (for node-gyp)
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: npm ci
          
    - name: Build
      run: npm run compile
